kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi

---
